### ISSUE TITLE
Invalid character in header content ["x-client-version"]

### ISSUE THREAD

**Issue by jcs090218** [emacs-grammarly/lsp-grammarly#1]
Getting this error after starting language server. This may be the upstream bug.

```
(node:19264) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["x-client-version"]
    at ClientRequest.setHeader (_http_outgoing.js:561:3)
    at new ClientRequest (_http_client.js:251:14)
    at request (https.js:313:10)
    at get (https.js:317:15)
    at initAsClient (c:\Users\JenChieh\AppData\Roaming\.emacs.d\.cache\lsp\npm\unofficial-grammarly-language-server-2\node_modules\unofficial-grammarly-language-server-2\node_modules\ws\lib\websocket.js:566:31)
    at new WebSocket (c:\Users\JenChieh\AppData\Roaming\.emacs.d\.cache\lsp\npm\unofficial-grammarly-language-server-2\node_modules\unofficial-grammarly-language-server-2\node_modules\ws\lib\websocket.js:71:7)
    at GrammarlyClient._connect (c:\Users\JenChieh\AppData\Roaming\.emacs.d\.cache\lsp\npm\unofficial-grammarly-language-server-2\node_modules\unofficial-grammarly-language-server-2\node_modules\unofficial-grammarly-api-2\dist\index.cjs.js:427:24)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:19264) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:19264) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by jcs090218** [comment]
I have a temporary workaround here, https://github.com/emacs-grammarly.

**Comment by jcs090218** [comment]
Resolved in my own form.
