### ISSUE TITLE
SocketError: Socket connection failed: NOT_AUTHORIZED

### ISSUE THREAD

**Issue by epichub** [emacs-grammarly/lsp-grammarly#12]
I am using the git version, and it is authorized with grammarly - but my lsp-grammarly is restarting every time i edit my tex document. I am also on macOS. I suspect this is an easy fix, given that I am quite the novice with npm/javascript..

```HOMEDIR/.emacs.d/.cache/lsp/npm/@emacs-grammarly/unofficial-grammarly-language-server/lib/node_modules/@emacs-grammarly/unofficial-grammarly-language-server/node_modules/@emacs-grammarly/unofficial-grammarly-api/dist/index.cjs.js:417
            throw new SocketError(this._statusCode, `Socket connection failed: ${this._statusMessage}`);
                  ^

SocketError: Socket connection failed: NOT_AUTHORIZED
    at GrammarlyClient._connect (HOMEDIR/.emacs.d/.cache/lsp/npm/@emacs-grammarly/unofficial-grammarly-language-server/lib/node_modules/@emacs-grammarly/unofficial-grammarly-language-server/node_modules/@emacs-grammarly/unofficial-grammarly-api/dist/index.cjs.js:417:19)
    at GrammarlyClient._queueOrSend (HOMEDIR/.emacs.d/.cache/lsp/npm/@emacs-grammarly/unofficial-grammarly-language-server/lib/node_modules/@emacs-grammarly/unofficial-grammarly-language-server/node_modules/@emacs-grammarly/unofficial-grammarly-api/dist/index.cjs.js:494:18)
    at HOMEDIR/.emacs.d/.cache/lsp/npm/@emacs-grammarly/unofficial-grammarly-language-server/lib/node_modules/@emacs-grammarly/unofficial-grammarly-language-server/node_modules/@emacs-grammarly/unofficial-grammarly-api/dist/index.cjs.js:390:18
    at new Promise (<anonymous>)
    at GrammarlyClient.send (HOMEDIR/.emacs.d/.cache/lsp/npm/@emacs-grammarly/unofficial-grammarly-language-server/lib/node_modules/@emacs-grammarly/unofficial-grammarly-language-server/node_modules/@emacs-grammarly/unofficial-grammarly-api/dist/index.cjs.js:388:16)
    at GrammarlyClient.sendWithErrorHandling (HOMEDIR/.emacs.d/.cache/lsp/npm/@emacs-grammarly/unofficial-grammarly-language-server/lib/node_modules/@emacs-grammarly/unofficial-grammarly-language-server/node_modules/@emacs-grammarly/unofficial-grammarly-api/dist/index.cjs.js:618:31)
    at GrammarlyClient.submitOT (HOMEDIR/.emacs.d/.cache/lsp/npm/@emacs-grammarly/unofficial-grammarly-language-server/lib/node_modules/@emacs-grammarly/unofficial-grammarly-language-server/node_modules/@emacs-grammarly/unofficial-grammarly-api/dist/index.cjs.js:710:21)
    at TextGrammarCheckHost.sync (HOMEDIR/.emacs.d/.cache/lsp/npm/@emacs-grammarly/unofficial-grammarly-language-server/lib/node_modules/@emacs-grammarly/unofficial-grammarly-language-server/dist/index.cjs.js:584:24)
    at TextGrammarCheckHost.setText (HOMEDIR/.emacs.d/.cache/lsp/npm/@emacs-grammarly/unofficial-grammarly-language-server/lib/node_modules/@emacs-grammarly/unofficial-grammarly-language-server/dist/index.cjs.js:527:19)
    at Function.update (HOMEDIR/.emacs.d/.cache/lsp/npm/@emacs-grammarly/unofficial-grammarly-language-server/lib/node_modules/@emacs-grammarly/unofficial-grammarly-language-server/dist/index.cjs.js:327:28) {
  code: 4001
}

Process grammarly-ls stderr finished
HOMEDIR/.emacs.d/.cache/lsp/npm/@emacs-grammarly/unofficial-grammarly-language-server/lib/node_modules/@emacs-grammarly/unofficial-grammarly-language-server/node_modules/@emacs-grammarly/unofficial-grammarly-api/dist/index.cjs.js:417
            throw new SocketError(this._statusCode, `Socket connection failed: ${this._statusMessage}`);
                  ^

SocketError: Socket connection failed: NOT_AUTHORIZED
    at GrammarlyClient._connect (HOMEDIR/.emacs.d/.cache/lsp/npm/@emacs-grammarly/unofficial-grammarly-language-server/lib/node_modules/@emacs-grammarly/unofficial-grammarly-language-server/node_modules/@emacs-grammarly/unofficial-grammarly-api/dist/index.cjs.js:417:19)
    at GrammarlyClient._queueOrSend (HOMEDIR/.emacs.d/.cache/lsp/npm/@emacs-grammarly/unofficial-grammarly-language-server/lib/node_modules/@emacs-grammarly/unofficial-grammarly-language-server/node_modules/@emacs-grammarly/unofficial-grammarly-api/dist/index.cjs.js:494:18)
    at HOMEDIR/.emacs.d/.cache/lsp/npm/@emacs-grammarly/unofficial-grammarly-language-server/lib/node_modules/@emacs-grammarly/unofficial-grammarly-language-server/node_modules/@emacs-grammarly/unofficial-grammarly-api/dist/index.cjs.js:390:18
    at new Promise (<anonymous>)
    at GrammarlyClient.send (HOMEDIR/.emacs.d/.cache/lsp/npm/@emacs-grammarly/unofficial-grammarly-language-server/lib/node_modules/@emacs-grammarly/unofficial-grammarly-language-server/node_modules/@emacs-grammarly/unofficial-grammarly-api/dist/index.cjs.js:388:16)
    at GrammarlyClient.start (HOMEDIR/.emacs.d/.cache/lsp/npm/@emacs-grammarly/unofficial-grammarly-language-server/lib/node_modules/@emacs-grammarly/unofficial-grammarly-language-server/node_modules/@emacs-grammarly/unofficial-grammarly-api/dist/index.cjs.js:676:21)
    at GrammarlyClient.onConnection [as _onConnection] (HOMEDIR/.emacs.d/.cache/lsp/npm/@emacs-grammarly/unofficial-grammarly-language-server/lib/node_modules/@emacs-grammarly/unofficial-grammarly-language-server/dist/index.cjs.js:450:32) {
  code: 4001
}

Process grammarly-ls stderr finished
```

**Comment by jcs090218** [comment]
I think the issue is from upstream. 😭 

See https://github.com/znck/grammarly/issues/183

**Comment by jcs090218** [comment]
Try logout and login, it resolved on my side!

**Comment by epichub** [comment]
Thanks this worked!
