### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by vzaliva** [emacs-grammarly/lsp-grammarly#24]
I could not get it work. I see it starting process `.emacs.d/.cache/lsp/npm/@emacs-grammarly/unofficial-grammarly-language-server/bin/unofficial-grammarly-language-server --stdio`.  `lsp-describe-session` shows the following:

![image](https://user-images.githubusercontent.com/86581/143667048-659388e9-db3c-4aaf-b858-3087847943b0.png)

`lsp-grammarly-login` shows "you already logged...".  Buffer `grammarly-ls` is empty. Buffer `grammarlly-ls::stderr` shows:

```
(node:596188) UnhandledPromiseRejectionWarning: Error: Socket connection failed: NOT_AUTHORIZED
    at GrammarlyClient._connect (/home/lord/.emacs.d/.cache/lsp/npm/@emacs-grammarly/unofficial-grammarly-language-server/lib/node_modules/@emacs-grammarly/unofficial-grammarly-language-server/node_modules/@emacs-grammarly/unofficial-grammarly-api/dist/index.cjs.js:417:19)
    at GrammarlyClient._queueOrSend (/home/lord/.emacs.d/.cache/lsp/npm/@emacs-grammarly/unofficial-grammarly-language-server/lib/node_modules/@emacs-grammarly/unofficial-grammarly-language-server/node_modules/@emacs-grammarly/unofficial-grammarly-api/dist/index.cjs.js:494:18)
    at /home/lord/.emacs.d/.cache/lsp/npm/@emacs-grammarly/unofficial-grammarly-language-server/lib/node_modules/@emacs-grammarly/unofficial-grammarly-language-server/node_modules/@emacs-grammarly/unofficial-grammarly-api/dist/index.cjs.js:390:18
    at new Promise (<anonymous>)
    at GrammarlyClient.send (/home/lord/.emacs.d/.cache/lsp/npm/@emacs-grammarly/unofficial-grammarly-language-server/lib/node_modules/@emacs-grammarly/unofficial-grammarly-language-server/node_modules/@emacs-grammarly/unofficial-grammarly-api/dist/index.cjs.js:388:16)
    at GrammarlyClient.sendWithErrorHandling (/home/lord/.emacs.d/.cache/lsp/npm/@emacs-grammarly/unofficial-grammarly-language-server/lib/node_modules/@emacs-grammarly/unofficial-grammarly-language-server/node_modules/@emacs-grammarly/unofficial-grammarly-api/dist/index.cjs.js:618:31)
    at GrammarlyClient.submitOT (/home/lord/.emacs.d/.cache/lsp/npm/@emacs-grammarly/unofficial-grammarly-language-server/lib/node_modules/@emacs-grammarly/unofficial-grammarly-language-server/node_modules/@emacs-grammarly/unofficial-grammarly-api/dist/index.cjs.js:710:21)
    at TextGrammarCheckHost.sync (/home/lord/.emacs.d/.cache/lsp/npm/@emacs-grammarly/unofficial-grammarly-language-server/lib/node_modules/@emacs-grammarly/unofficial-grammarly-language-server/dist/index.cjs.js:584:24)
    at TextGrammarCheckHost.setText (/home/lord/.emacs.d/.cache/lsp/npm/@emacs-grammarly/unofficial-grammarly-language-server/lib/node_modules/@emacs-grammarly/unofficial-grammarly-language-server/dist/index.cjs.js:527:19)
    at Function.update (/home/lord/.emacs.d/.cache/lsp/npm/@emacs-grammarly/unofficial-grammarly-language-server/lib/node_modules/@emacs-grammarly/unofficial-grammarly-language-server/dist/index.cjs.js:327:28)
(node:596188) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:596188) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I am very interested in making this work and providing any debugging help required.

**Comment by vzaliva** [comment]
Could be related to: https://github.com/znck/grammarly/issues/183

**Comment by vzaliva** [comment]
It was same issues as  znck/grammarly#183
