### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by vzaliva** [emacs-grammarly/lsp-grammarly#32]
After recent update from MELPA I got:

```Error: Cannot find module 'node:perf_hooks'
Require stack:
- /home/lord/.emacs.d/.cache/lsp/npm/@emacs-grammarly/grammarly-languageserver/lib/node_modules/@emacs-grammarly/grammarly-languageserver/node_modules/@grammarly/sdk/lib/index.node.js
- /home/lord/.emacs.d/.cache/lsp/npm/@emacs-grammarly/grammarly-languageserver/lib/node_modules/@emacs-grammarly/grammarly-languageserver/dist/index.cjs.js
- /home/lord/.emacs.d/.cache/lsp/npm/@emacs-grammarly/grammarly-languageserver/lib/node_modules/@emacs-grammarly/grammarly-languageserver/bin/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/lord/.emacs.d/.cache/lsp/npm/@emacs-grammarly/grammarly-languageserver/lib/node_modules/@emacs-grammarly/grammarly-languageserver/node_modules/@grammarly/sdk/lib/index.node.js:17:93)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/lord/.emacs.d/.cache/lsp/npm/@emacs-grammarly/grammarly-languageserver/lib/node_modules/@emacs-grammarly/grammarly-languageserver/node_modules/@grammarly/sdk/lib/index.node.js',
    '/home/lord/.emacs.d/.cache/lsp/npm/@emacs-grammarly/grammarly-languageserver/lib/node_modules/@emacs-grammarly/grammarly-languageserver/dist/index.cjs.js',
    '/home/lord/.emacs.d/.cache/lsp/npm/@emacs-grammarly/grammarly-languageserver/lib/node_modules/@emacs-grammarly/grammarly-languageserver/bin/server.js'
  ]
}

Process grammarly-ls stderr<1> finished

Process grammarly-ls stderr finished
```

**Comment by vzaliva** [comment]
In *Messages* buffer:

```LSP :: grammarly-ls has exited (exited abnormally with code 1)
Server grammarly-ls:2448075/starting exited with status exit(check corresponding stderr buffer for details). Do you want to restart it? (y or n) n
```

**Comment by jcs090218** [comment]
Hmm... this does not seem right. 

Is this something with your node environment? 😕 Sorry I am trying to guess here, since I can't reproduce this on my machine (Windows 10).

**Comment by vzaliva** [comment]
Everything was working before the last update - so the environment is OK.
I do not know NPM, but it looks like Grammarly is missing some dependency. Are there new dependencies?
I  guess they should be installed when emacs package is installed or initalized.

**Comment by vzaliva** [comment]
I've removed ~/.emacs.d/.cache/lsp/npm and restarted. Now the message is more clear:

```Error: Cannot find module 'node:perf_hooks'
Require stack:
- /home/lord/.emacs.d/.cache/lsp/npm/@emacs-grammarly/grammarly-languageserver/lib/node_modules/@emacs-grammarly/grammarly-languageserver/node_modules/@grammarly/sdk/lib/index.node.js
- /home/lord/.emacs.d/.cache/lsp/npm/@emacs-grammarly/grammarly-languageserver/lib/node_modules/@emacs-grammarly/grammarly-languageserver/dist/index.cjs.js
- /home/lord/.emacs.d/.cache/lsp/npm/@emacs-grammarly/grammarly-languageserver/lib/node_modules/@emacs-grammarly/grammarly-languageserver/bin/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/lord/.emacs.d/.cache/lsp/npm/@emacs-grammarly/grammarly-languageserver/lib/node_modules/@emacs-grammarly/grammarly-languageserver/node_modules/@grammarly/sdk/lib/index.node.js:17:93)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/lord/.emacs.d/.cache/lsp/npm/@emacs-grammarly/grammarly-languageserver/lib/node_modules/@emacs-grammarly/grammarly-languageserver/node_modules/@grammarly/sdk/lib/index.node.js',
    '/home/lord/.emacs.d/.cache/lsp/npm/@emacs-grammarly/grammarly-languageserver/lib/node_modules/@emacs-grammarly/grammarly-languageserver/dist/index.cjs.js',
    '/home/lord/.emacs.d/.cache/lsp/npm/@emacs-grammarly/grammarly-languageserver/lib/node_modules/@emacs-grammarly/grammarly-languageserver/bin/server.js'
  ]
}
```

The module `node:perf_hooks` is missing. How can I fix it?

**Comment by jcs090218** [comment]
Here is the list of dependencies, https://github.com/emacs-grammarly/grammarly-language-server/blob/main/packages/grammarly-languageserver/package.json.

I think the error is cause by [@grammarly/sdk](https://www.npmjs.com/package/@grammarly/sdk)? 😕

**Comment by jcs090218** [comment]
I have upgraded the language server to `0.011`. But I don't know if this would resolve the issue for you!

Can you retry to upgrade `lsp-grammarly` and redownload the language server once again? Thanks! 😖

**Comment by vzaliva** [comment]
I've reinstalled lsp-grammarly package from MELPA. Then I removed `~/.emacs.d/.cache/lsp/npm` directory and restarted my emacs. It re-installed lps-server. Here is content of `*lsp-install: /usr/bin/npm*` buffer:

```
/usr/bin/npm -g --prefix /home/lord/.emacs.d/.cache/lsp/npm/\@emacs-grammarly/grammarly-languageserver install \@emacs-grammarly/grammarly-languageserver
/home/lord/.emacs.d/.cache/lsp/npm/@emacs-grammarly/grammarly-languageserver/bin/grammarly-languageserver -> /home/lord/.emacs.d/.cache/lsp/npm/@emacs-grammarly/grammarly-languageserver/lib/node_modules/@emacs-grammarly/grammarly-languageserver/bin/server.js
+ @emacs-grammarly/grammarly-languageserver@0.0.11
added 20 packages from 10 contributors in 4.61s
```
It is still failing to start with the following error:

`Error: Cannot find module 'node:perf_hooks'`

I do not see it in the list of node modules installed:

```
ls /home/lord/.emacs.d/.cache/lsp/npm/@emacs-grammarly/grammarly-languageserver/lib/node_modules/@emacs-grammarly/grammarly-languageserver/node_modules
@grammarly      htmlparser2       vscode-languageserver               whatwg-url
dom-serializer  inversify         vscode-languageserver-protocol      
domelementtype  node-fetch        vscode-languageserver-textdocument  
domhandler      reflect-metadata  vscode-languageserver-types         
domutils        tr46              web-tree-sitter                     
entities        vscode-jsonrpc    webidl-conversions 
```

while it is mentioned in `~/.emacs.d/.cache/lsp/npm/@emacs-grammarly/grammarly-languageserver/lib/node_modules/@emacs-grammarly/grammarly-languageserver/node_modules/@grammarly/sdk/lib/index.node.js`

So there is a clear installation issue.
There are 2 `node_module` directories:

1. `~/.emacs.d/.cache/lsp/npm/@emacs-grammarly/grammarly-languageserver/lib/node_modules`
2. `~/.emacs.d/.cache/lsp/npm/@emacs-grammarly/grammarly-languageserver/lib/node_modules/@emacs-grammarly/grammarly-languageserver/node_modules`

The first one contains only `@emacs-grammarly`.

**Comment by jcs090218** [comment]
Hmmm... this seems like a bug from node runtime, see https://stackoverflow.com/questions/68188009/module-not-found-cant-resolve-perf-hooks-reactjs.

What node version are you using? Maybe try the LTS version node 16?

**Comment by vzaliva** [comment]
Upgrading NodeJS to 16 LTS solved the problem.
In my defence, I was using the default version of NodeJS provided by Ubuntu 20.04.4 LTS, which was v12.22.12.
