### ISSUE TITLE
Server errors

### ISSUE THREAD

**Issue by agzam** [emacs-grammarly/lsp-grammarly#37]
This seems to be an upstream issue, still reporting it here since I use it only in Emacs.

The server failing with: 

    Node.js v18.3.0
    (node:46789) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
    (Use `node --trace-warnings ...` to show where the warning was created)
    node:internal/deps/undici/undici:4813
                throw new TypeError("Failed to parse URL from " + input, { cause: err });
                    ^

    TypeError: Failed to parse URL from /Users/ag/.emacs-profiles/.emacs-doom.d/.local/etc/lsp/npm/@emacs-grammarly/grammarly-languageserver/lib/node_modules/@emacs-grammarly/grammarly-languageserver/node_modules/web-tree-sitter/tree-sitter.wasm
        at new Request (node:internal/deps/undici/undici:4813:19)
        at Agent.fetch2 (node:internal/deps/undici/undici:5505:29)
        ... 4 lines matching cause stack trace ...
        at new Promise (<anonymous>)
        at Parser.init (/Users/ag/.emacs-profiles/.emacs-doom.d/.local/etc/lsp/npm/@emacs-grammarly/grammarly-languageserver/lib/node_modules/@emacs-grammarly/grammarly-languageserver/node_modules/web-tree-sitter/tree-sitter.js:1:332)
        at createParserInner (/Users/ag/.emacs-profiles/.emacs-doom.d/.local/etc/lsp/npm/@emacs-grammarly/grammarly-languageserver/lib/node_modules/@emacs-grammarly/grammarly-languageserver/node_modules/@emacs-grammarly/grammarly-richtext-encoder/dist/index.cjs:449:42)
        at Object.createParser (/Users/ag/.emacs-profiles/.emacs-doom.d/.local/etc/lsp/npm/@emacs-grammarly/grammarly-languageserver/lib/node_modules/@emacs-grammarly/grammarly-languageserver/node_modules/@emacs-grammarly/grammarly-richtext-encoder/dist/index.cjs:445:20) {
    [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
        at new NodeError (node:internal/errors:377:5)
        at URL.onParseError (node:internal/url:563:9)
        at new URL (node:internal/url:643:5)
        at new Request (node:internal/deps/undici/undici:4811:25)
        at Agent.fetch2 (node:internal/deps/undici/undici:5505:29)
        at Object.fetch (node:internal/deps/undici/undici:6332:20)
        at fetch (node:internal/bootstrap/pre_execution:196:25)
        at /Users/ag/.emacs-profiles/.emacs-doom.d/.local/etc/lsp/npm/@emacs-grammarly/grammarly-languageserver/lib/node_modules/@emacs-grammarly/grammarly-languageserver/node_modules/web-tree-sitter/tree-sitter.js:1:15192
        at /Users/ag/.emacs-profiles/.emacs-doom.d/.local/etc/lsp/npm/@emacs-grammarly/grammarly-languageserver/lib/node_modules/@emacs-grammarly/grammarly-languageserver/node_modules/web-tree-sitter/tree-sitter.js:1:15413
        at new Promise (<anonymous>) {
        input: '/Users/aibragim/.emacs-profiles/.emacs-doom.d/.local/etc/lsp/npm/@emacs-grammarly/grammarly-languageserver/lib/node_modules/@emacs-grammarly/grammarly-languageserver/node_modules/web-tree-sitter/tree-sitter.wasm',
        code: 'ERR_INVALID_URL'
    }
    }

**Comment by agzam** [comment]
It looks like it's failing in node v18. Works fine in v16. I apologize for the noise, this is not an issue with lsp-grammarly. Closing it.

**Comment by kiennq** [comment]
Btw, manually adding the ` --no-experimental-fetch` will solve this problem as well

**Comment by agzam** [comment]
> Btw, manually adding the ` --no-experimental-fetch` will solve this problem as well

Can you elaborate, where this flag needs to be added?

**Comment by kiennq** [comment]
> > Btw, manually adding the ` --no-experimental-fetch` will solve this problem as well
> 
> Can you elaborate, where this flag needs to be added?

In the script that launches `emacs-grammarly`, for example under `.emacs.d\.cache\lsp\npm\@emacs-grammarly\unofficial-grammarly-language-server`

**Comment by Martinsos** [comment]
Just encountered this! Is there any advice how to get around this?

While my default node on the machine is 16, for some reason I see that grammarly-ls is using node 18 (in its error message) -> I am not sure how to specify for grammarly-ls to use a specific node version?

Regarding that --no-experimental-fetch flag -> is there any way to possibly set it in emacs, so we don't have to manually edit that launcher file? Or would it make sense that maintainers add it to the grammarly-languageserver script?

**Comment by jcs090218** [comment]
Hi @Martinsos!

I don't think there is an option to set the node version. However, there is a hacky way to do this. The server is activated by shell script (depends on your OS), so you could change the node path there. Here is the shell script on my machine, yours should looks similar 

```sh
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*|*MINGW*|*MSYS*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/node_modules/@emacs-grammarly/grammarly-languageserver/bin/server.js" "$@"
else 
  exec node  "$basedir/node_modules/@emacs-grammarly/grammarly-languageserver/bin/server.js" "$@"
fi
```

If you don't want to pollute the file, you can set the activation file manually through variable `lsp-grammarly-server-path`. Hope the information helps!
