### ISSUE TITLE
Stopped working?

### ISSUE THREAD

**Issue by agzam** [emacs-grammarly/lsp-grammarly#46]
I just reinstalled OSX on my machine from scratch, and for some reason, the package is no longer working. 

When I run M-x lsp the first time, it would say that the server is not found and prompts me if I want to install it. I said, 'yes', and it installed it, here's the installation log:

```
-*- mode: compilation; default-directory: "/private/tmp/" -*-
Comint started at Sun Nov  6 15:08:38

/Users/ag/.nvm/versions/node/v18.12.1/bin/npm -g --prefix /Users/ag/.emacs.d/.local/etc/lsp/npm/\@emacs-grammarly/grammarly-languageserver install \@emacs-grammarly/grammarly-languageserver

added 23 packages, and audited 24 packages in 3s

6 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Comint finished at Sun Nov  6 15:08:41
```

But then, it fails with the following error (from `*grammarly-ls::stderr*` buffer:

```
(node:3713) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
node:internal/deps/undici/undici:11118
    Error.captureStackTrace(err, this);
          ^

TypeError: Failed to parse URL from /Users/ag/.emacs.d/.local/etc/lsp/npm/@emacs-grammarly/grammarly-languageserver/lib/node_modules/@emacs-grammarly/grammarly-languageserver/node_modules/web-tree-sitter/tree-sitter.wasm
    at Object.fetch (node:internal/deps/undici/undici:11118:11) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:393:5)
      at URL.onParseError (node:internal/url:565:9)
      at new URL (node:internal/url:645:5)
      at new Request (node:internal/deps/undici/undici:9472:25)
      at Agent.fetch2 (node:internal/deps/undici/undici:10291:25)
      at Object.fetch (node:internal/deps/undici/undici:11116:28)
      at fetch (node:internal/process/pre_execution:216:25)
      at /Users/ag/.emacs.d/.local/etc/lsp/npm/@emacs-grammarly/grammarly-languageserver/lib/node_modules/@emacs-grammarly/grammarly-languageserver/node_modules/web-tree-sitter/tree-sitter.js:1:15192
      at /Users/ag/.emacs.d/.local/etc/lsp/npm/@emacs-grammarly/grammarly-languageserver/lib/node_modules/@emacs-grammarly/grammarly-languageserver/node_modules/web-tree-sitter/tree-sitter.js:1:15413
      at new Promise (<anonymous>) {
    input: '/Users/ag/.emacs.d/.local/etc/lsp/npm/@emacs-grammarly/grammarly-languageserver/lib/node_modules/@emacs-grammarly/grammarly-languageserver/node_modules/web-tree-sitter/tree-sitter.wasm',
    code: 'ERR_INVALID_URL'
  }
}

Node.js v18.12.1

Process grammarly-ls stderr finished
```

Previously, it worked fine with a similar configuration. Can someone guide me on how I could work around this?

**Comment by jcs090218** [comment]
I think is the same error in #37? Make sure you have node 16 installed and not node 18.

**Comment by agzam** [comment]
Hmm... I swear, at some point, I switched to node 18 yet it kept working. I must have made a mistake thinking it was using 18, while it was grabbing it from the 16's folder.

Do you know if there's a way to configure the npm folder, specifically for grammarly-lsp-server, so I can keep using v18 for everything else?

**Comment by jcs090218** [comment]
Unfortunately, I am not very familiar with the differences between each node version. I will post something here if I have discovered anything!

**Comment by tmonck** [comment]
[I would look into nvm and you can](https://github.com/nvm-sh/nvm#nvmrc) you can define a file that allows you to override the default node version for a given directory.
