### ISSUE TITLE
grammarly-ls crashes

### ISSUE THREAD

**Issue by dexter2206** [emacs-grammarly/lsp-grammarly#49]
When attempting to use LSP with Grammarly and `markdown-mode`, `grammarly-ls` crashes with the following trraceback:

```text
node:internal/deps/undici/undici:11413
    Error.captureStackTrace(err, this);
          ^

TypeError: Failed to parse URL from /home/dexter/.config/emacs/.local/etc/lsp/npm/@emacs-grammarly/grammarly-languageserver/lib/node_modules/@emacs-grammarly/grammarly-languageserver/node_modules/web-tree-sitter/tree-sitter.wasm
    at Object.fetch (node:internal/deps/undici/undici:11413:11) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:399:5)
      at URL.onParseError (node:internal/url:566:9)
      at new URL (node:internal/url:646:5)
      at new Request (node:internal/deps/undici/undici:7002:25)
      at fetch2 (node:internal/deps/undici/undici:10554:25)
      at Object.fetch (node:internal/deps/undici/undici:11411:18)
      at fetch (node:internal/process/pre_execution:230:25)
      at /home/dexter/.config/emacs/.local/etc/lsp/npm/@emacs-grammarly/grammarly-languageserver/lib/node_modules/@emacs-grammarly/grammarly-languageserver/node_modules/web-tree-sitter/tree-sitter.js:1:15192
      at /home/dexter/.config/emacs/.local/etc/lsp/npm/@emacs-grammarly/grammarly-languageserver/lib/node_modules/@emacs-grammarly/grammarly-languageserver/node_modules/web-tree-sitter/tree-sitter.js:1:15413
      at new Promise (<anonymous>) {
    input: '/home/dexter/.config/emacs/.local/etc/lsp/npm/@emacs-grammarly/grammarly-languageserver/lib/node_modules/@emacs-grammarly/grammarly-languageserver/node_modules/web-tree-sitter/tree-sitter.wasm',
    code: 'ERR_INVALID_URL'
  }
}

Node.js v18.15.0

Process grammarly-ls stderr finished
```

Interestingly, this _exclusively_ happens when using `markdown-mode`. Everything works fine when using LSP mode and Grammarly with TeX files or text files.

I'm too new to emacs and LSPs to debug this further and would really appreciate if someone could point me in the correct direction to solving this.

**Comment by jcs090218** [comment]
I think the language server is only compatible v16, can you downgrade your node version to v16? Thanks!

**Comment by kamushadenes** [comment]
I had the same behavior, and downgrading to v16 fixed it.

**Comment by jcs090218** [comment]
Thanks for the confirmation. ❤️ I think the issue can be closed now.
